Moderinzing build scripts

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,17 +22,16 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      # TODO
-      # - name: Lint the project
-      #   run: npm run lint
+      - name: Lint the project
+        run: npm run lint
 
-      # - name: Build the project
-      #   run: npm run build
+      - name: Build the project
+        run: npm run build
 
-      # - name: List, audit, fix outdated dependencies and build again
-      #   run: |
-      #     npm list --outdated
-      #     npm audit || true  # ignore failures
-      #     npm audit fix || true
-      #     npm list --outdated
-      #     npm run build
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          npm list --outdated
+          npm audit || true  # ignore failures
+          npm audit fix || true
+          npm list --outdated
+          npm run build
